[kafka]
bootstrap_servers = "localhost:9092"
topic = "mytopic"

[postgres]
host = "localhost"
database = "mydatabase"
user = "myuser"
password = "mypassword"

[spark]
app_name = "kafka-on-k8s-consumer"
packages = [
    "org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2",
    "org.postgresql:postgresql:42.2.18"
]

[logging]
level = "INFO"
